April 2025 Update with many fixes
Signed-off-by: rokibhasansagar <10854164+rokibhasansagar@users.noreply.github.com>

diff --git a/zig-nightly-bin/PKGBUILD b/zig-nightly-bin/PKGBUILD
--- a/zig-nightly-bin/PKGBUILD
+++ b/zig-nightly-bin/PKGBUILD
@@ -1,13 +1,13 @@
 #!/hint/bash
 
 pkgname=zig-nightly-bin
-pkgver=0.14.0_dev.1671.g085cc54aa
-pkgrel=2
-pkgdesc='A general-purpose programming language and toolchain for maintaining robust, optimal, and reusable software (nightly)'
+pkgver=0.14.0_dev.3062.ff551374a
+pkgrel=3
+pkgdesc="A general-purpose programming language and toolchain for maintaining robust, optimal, and reusable software (nightly build)"
 arch=('x86_64' 'aarch64')
-url='https://ziglang.org/'
+url="https://ziglang.org/"
 license=('MIT')
-provides=("zig")
+provides=('zig')
 conflicts=('zig')
 makedepends=('jq')
 optdepends=('curl: for downloading the latest version'
@@ -31,7 +31,7 @@ _sanitize_version() {
 }
 
 pkgver() {
-    _sanitize_version "$(_get_latest_version)"
+    echo $(_sanitize_version "$(_get_latest_version)")
 }
 
 _get_download_url() {
@@ -62,7 +62,18 @@ source=("zig-$pkgver-$CARCH-linux.tar.xz::$(_get_download_url)")
 sha256sums=("$(_get_sha256sum)")
 
 package() {
-    cd "$srcdir/zig-linux-$CARCH-$(_get_latest_version)"
+    local latest_version=$(_get_latest_version)
+    local srcdir1="$srcdir/zig-linux-$CARCH-$latest_version"
+    local srcdir2="$srcdir/zig-linux-$CARCH-$pkgver"
+    if [ -d "$srcdir1" ]; then
+        cd "$srcdir1"
+    elif [ -d "$srcdir2" ]; then
+        cd "$srcdir2"
+    else
+        echo "Error: Neither source directory found ($srcdir1 or $srcdir2)" >&2
+        exit 1
+    fi
+
 
     install -dm755 "$pkgdir/usr/lib/zig"
     cp -a * "$pkgdir/usr/lib/zig/"
@@ -76,4 +87,3 @@ package() {
         install -Dm644 doc/langref.html "$pkgdir/usr/share/doc/zig/langref.html"
     fi
 }
-
